# Generated by Django 4.2.2 on 2024-03-04 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='doc',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
